<?xml version="1.0"?>

<!-- DTD for the BIF format -->
<!DOCTYPE BIF [
      <!ELEMENT BIF ( NETWORK )*>
      <!ELEMENT PROPERTY (#PCDATA)>
      <!ELEMENT TYPE (#PCDATA)>
      <!ELEMENT VALUE (#PCDATA)>
      <!ELEMENT NAME (#PCDATA)>
      <!ELEMENT NETWORK
          ( NAME, ( PROPERTY | VARIABLE | PROBABILITY )* )>
        <!ATTLIST NETWORK size CDATA #REQUIRED>
      <!ELEMENT VARIABLE ( NAME, TYPE, ( VALUE |  PROPERTY )* ) >
      <!ELEMENT PROBABILITY
          ( FOR | GIVEN | TABLE | ENTRY | DEFAULT | PROPERTY )* >
      <!ELEMENT FOR (#PCDATA)>
      <!ELEMENT GIVEN (#PCDATA)>
      <!ELEMENT TABLE (#PCDATA)>
      <!ELEMENT DEFAULT (TABLE)>
      <!ELEMENT ENTRY ( VALUE* , TABLE )>
]>
<BIF>
<NETWORK size = "10" >
<NAME>Bayes network</NAME>
<!-- Variables -->
<VARIABLE>
    <NAME>YPL256C</NAME>
    <TYPE>discrete</TYPE>
    <PROPERTY>position = (270, 200)</PROPERTY>
</VARIABLE>
<VARIABLE>
    <NAME>YPL163C</NAME>
    <TYPE>discrete</TYPE>
    <PROPERTY>position = (200, 200)</PROPERTY>
</VARIABLE>
<VARIABLE>
    <NAME>YIL066C</NAME>
    <TYPE>discrete</TYPE>
    <PROPERTY>position = (221, 266)</PROPERTY>
</VARIABLE>
<VARIABLE>
    <NAME>YIL140W</NAME>
    <TYPE>discrete</TYPE>
    <PROPERTY>position = (300, 300)</PROPERTY>
</VARIABLE>
<VARIABLE>
    <NAME>YMR199W</NAME>
    <TYPE>discrete</TYPE>
    <PROPERTY>position = (143, 158)</PROPERTY>
</VARIABLE>
<VARIABLE>
    <NAME>YER001W</NAME>
    <TYPE>discrete</TYPE>
    <PROPERTY>position = (143, 241)</PROPERTY>
</VARIABLE>
<VARIABLE>
    <NAME>YJL187C</NAME>
    <TYPE>discrete</TYPE>
    <PROPERTY>position = (221, 133)</PROPERTY>
</VARIABLE>
<!-- Probability distributions -->
<PROBABILITY>
    <FOR>YPL256C</FOR>
</PROBABILITY>
<PROBABILITY>
    <FOR>YPL163C</FOR>
    <GIVEN>YPL256C</GIVEN>
    <GIVEN>YIL066C</GIVEN>
    <GIVEN>YER001W</GIVEN>
    <GIVEN>YMR199W</GIVEN>
</PROBABILITY>
<PROBABILITY>
    <FOR>YIL066C</FOR>
    <GIVEN>YPL256C</GIVEN>
</PROBABILITY>
<PROBABILITY>
    <FOR>YIL140W</FOR>
    <GIVEN>YJL187C</GIVEN>
    <GIVEN>YMR199W</GIVEN>
</PROBABILITY>
<PROBABILITY>
    <FOR>YMR199W</FOR>
    <GIVEN>YPL256C</GIVEN>
</PROBABILITY>
<PROBABILITY>
    <FOR>YER001W</FOR>
    <GIVEN>YPL256C</GIVEN>
    <GIVEN>YIL066C</GIVEN>
</PROBABILITY>
<PROBABILITY>
    <FOR>YJL187C</FOR>
    <GIVEN>YPL163C</GIVEN>
</PROBABILITY>
</NETWORK>
</BIF>
